name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"
      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"

      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"

      - name: Send Email
        uses: hilarion5/send-mail@v1
        if: always()
        with:
          smtp-server: smtp.example.com
          smtp-port: 465
          smtp-secure: true
          from-email: sender@example.com
          to-email: recipient1@example.com,recipient2@example.com
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Automated API Tests Failed in ${{ github.workflow }} on ${{ github.sha }}"
          body: This is a test email sent from GitHub Actions.
          