name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"
      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"

      - name: Run API tests
        run: |
          postman collection run "25376308-0e2d67f1-e1c0-4c0e-8243-d038954ae9df"

      - name: Send email notification on failure (if job fails)
        uses: smehta/github-action-smtp@v1.1.0  # Replace with your chosen email sending action
        if: always()  # Only run this step if the previous steps failed
        env:
          # Configure email sending details based on the action's requirements
          # (replace placeholders with your actual values)
          SMTP_HOST: smtp.gmail.com
          SMTP_PORT: 465
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          EMAIL_RECIPIENTS: "recipient1@example.com,recipient2@example.com"
          EMAIL_SUBJECT: "Automated API Tests Failed in ${{ github.workflow }} on ${{ github.sha }}"
          EMAIL_BODY: "The automated API tests failed in the '${{ github.workflow }}' workflow for commit ${{ github.sha }}. See the workflow run for details: ${{ github.action_url }}"

      